### ISSUE TITLE
it is plugin or mapbox problem ?

### ISSUE THREAD

**Issue by AliCihan** [RoPP/nodebb-plugin-osm-map#7]
We do not see a map for some time, we thought it is a temporary problem but I guess mapbox stopped working?

![Screen Shot 2020-05-13 at 10 07 41 PM](https://user-images.githubusercontent.com/52054408/81884678-77f57800-9566-11ea-9c4b-6370e1cf67d4.png)

**Comment by AliCihan** [comment]
**UPDATE:** this change solved the issue for us... 

@freestylemaster created a PR... FYI... 

https://github.com/RoPP/nodebb-plugin-osm-map/pull/8/commits/8555240e10520cdf058bf3a267fc6ce44e193133

**Comment by RoPP** [comment]
Indeed, mapbox stopped its classic style api recently.

Thank you for the report and the fix.
